language: r
sudo: false
latex: false
pandoc: false
cache: packages
r_github_packages:
- cran/yaml
- yufree/scifetch
- rstudio/blogdown
before_install:
- git config --global user.email "yufree@live.cn"
- git config --global user.name "yufree"
- git checkout -b 'waiting'
script:
- Rscript R/fetch.R
after_success:
- git add --all *
- git commit -m "Daily update"
- curl --include --request POST --data '{"title":"Created via API","body":"daily update","head":"waiting","base":"master"}' "https://api.github.com/repos/yufree/daily/pulls?access_token=${GITHUB_PAT}"
