on:
  schedule:
    - cron:  '0 0 * * *'
name: dailyupdate

jobs:
  fetch-rss:
    runs-on: macOS-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-R-packages
      - name: Fetch RSS
        run: |
          Rscript R/fetch.R
      - name: Push results
        run: |
          git add .
          git commit -m "Daily Update"
          git push -q https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:master

